name: Release Charts

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/helm-chart-poc

on:
  push:
    branches:
      - main
permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.3

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.4.0
      #   with:
      #     charts_dir: ./
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.HELM_SECRET }}
          logout: false
      - name: Package Helm Chart
        run: |
          helm package .
          helm push *.tgz oci://ghcr.io/github-actions/helm-chart-poc